spring:
  config:
    import: optional:file:/config/profiler-application.yml
  # in docker, mounted from server file path in opt/
  data:
    mongodb:
      host: mongo
      port: 27017
      database: profiler
      username: profiler_app
      password: ${MONGO_PWD}
      authentication-database: profiler

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  security:
    swagger-public: false
    swagger-token: "n/a"
    swagger-url: "n/a"

logging:
  file:
    name: /app/logs/profiler-backend.log
