spring:
  config:
    import: optional:file:/config/profiler-application.yml
  # in docker, mounted from server file path in opt/
  data:
    mongodb:
      host: mongo
      port: 27017
      database: profiler
      username: profiler_app
      password: ${MONGO_PWD}
      authentication-database: profiler

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  security:
    swagger-public: true
    swagger-url: https://api.lan
  client:
    n8n:
      base-url: "http://n8n:5678/webhook"

logging:
  file:
    name: /app/logs/profiler-backend.log
  level:
    org.springframework.web.reactive.function.client: TRACE
